const githubProjects = [
  {
    id: 1,
    title: 'bilan-claude-code-08112025',
    client: 'GitHub Repository',
    industry: 'JavaScript',
    duration: '1 day ago',
    team: '1 contributor',
    role: 'Owner',
    challenge: 'Project focused on JavaScript development.',
    solution: ['Codebase', 'Configuration', 'Documentation'],
    technologies: ['JavaScript', 'Node.js', 'Git'],
    metrics: [
      { label: 'Stars', value: '0', icon: 'Star', color: 'text-yellow-500' },
      { label: 'Forks', value: '0', icon: 'GitFork', color: 'text-blue-500' },
      { label: 'Activity', value: 'Recent', icon: 'Zap', color: 'text-green-500' },
    ],
    testimonial: {
      text: 'Recent activity on this repository.',
      author: 'Ebubekir ARTI',
    },
    featured: true,
    url: 'https://github.com/Anonyme-00152/bilan-claude-code-08112025',
  },
  {
    id: 2,
    title: 'bilancompetence.ai',
    client: 'GitHub Repository',
    industry: 'TypeScript',
    duration: '1 day ago',
    team: '1 contributor',
    role: 'Owner',
    challenge: 'Project focused on TypeScript development.',
    solution: ['Codebase', 'Configuration', 'Documentation'],
    technologies: ['TypeScript', 'React', 'Next.js'],
    metrics: [
      { label: 'Stars', value: '0', icon: 'Star', color: 'text-yellow-500' },
      { label: 'Forks', value: '0', icon: 'GitFork', color: 'text-blue-500' },
      { label: 'Activity', value: 'Recent', icon: 'Zap', color: 'text-green-500' },
    ],
    testimonial: {
      text: 'Recent activity on this repository.',
      author: 'Ebubekir ARTI',
    },
    featured: true,
    url: 'https://github.com/Anonyme-00152/bilancompetence.ai',
  },
  {
    id: 3,
    title: 'bilan-08112025',
    client: 'GitHub Repository',
    industry: 'TypeScript',
    duration: '1 day ago',
    team: '1 contributor',
    role: 'Owner',
    challenge: 'Project focused on TypeScript development.',
    solution: ['Codebase', 'Configuration', 'Documentation'],
    technologies: ['TypeScript', 'Node.js', 'Express'],
    metrics: [
      { label: 'Stars', value: '0', icon: 'Star', color: 'text-yellow-500' },
      { label: 'Forks', value: '0', icon: 'GitFork', color: 'text-blue-500' },
      { label: 'Activity', value: 'Recent', icon: 'Zap', color: 'text-green-500' },
    ],
    testimonial: {
      text: 'Recent activity on this repository.',
      author: 'Ebubekir ARTI',
    },
    featured: false,
    url: 'https://github.com/Anonyme-00152/bilan-08112025',
  },
  {
    id: 4,
    title: 'bilan-071120252207',
    client: 'GitHub Repository',
    industry: 'TypeScript',
    duration: '2 days ago',
    team: '1 contributor',
    role: 'Owner',
    challenge: 'Project focused on TypeScript development.',
    solution: ['Codebase', 'Configuration', 'Documentation'],
    technologies: ['TypeScript', 'Next.js', 'Tailwind'],
    metrics: [
      { label: 'Stars', value: '0', icon: 'Star', color: 'text-yellow-500' },
      { label: 'Forks', value: '0', icon: 'GitFork', color: 'text-blue-500' },
      { label: 'Activity', value: 'Recent', icon: 'Zap', color: 'text-green-500' },
    ],
    testimonial: {
      text: 'Recent activity on this repository.',
      author: 'Ebubekir ARTI',
    },
    featured: false,
    url: 'https://github.com/Anonyme-00152/bilan-071120252207',
  },
  {
    id: 5,
    title: 'bilan-test-2147',
    client: 'GitHub Repository',
    industry: 'TypeScript',
    duration: '2 days ago',
    team: '1 contributor',
    role: 'Owner',
    challenge: 'Project focused on TypeScript development.',
    solution: ['Codebase', 'Configuration', 'Documentation'],
    technologies: ['TypeScript', 'React', 'Vite'],
    metrics: [
      { label: 'Stars', value: '0', icon: 'Star', color: 'text-yellow-500' },
      { label: 'Forks', value: '0', icon: 'GitFork', color: 'text-blue-500' },
      { label: 'Activity', value: 'Recent', icon: 'Zap', color: 'text-green-500' },
    ],
    testimonial: {
      text: 'Recent activity on this repository.',
      author: 'Ebubekir ARTI',
    },
    featured: false,
    url: 'https://github.com/Anonyme-00152/bilan-test-2147',
  },
  {
    id: 6,
    title: 'bilancompetence.ai.studio',
    client: 'GitHub Repository',
    industry: 'JavaScript',
    duration: '2 days ago',
    team: '1 contributor',
    role: 'Owner',
    challenge: 'Project focused on JavaScript development.',
    solution: ['Codebase', 'Configuration', 'Documentation'],
    technologies: ['JavaScript', 'Sanity', 'Next.js'],
    metrics: [
      { label: 'Stars', value: '0', icon: 'Star', color: 'text-yellow-500' },
      { label: 'Forks', value: '0', icon: 'GitFork', color: 'text-blue-500' },
      { label: 'Activity', value: 'Recent', icon: 'Zap', color: 'text-green-500' },
    ],
    testimonial: {
      text: 'Recent activity on this repository.',
      author: 'Ebubekir ARTI',
    },
    featured: false,
    url: 'https://github.com/Anonyme-00152/bilancompetence.ai.studio',
  },
];

export default githubProjects;
